// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvFARR9V-OkyVjIlk7Dr1SeXEbBW6lWk4',
    appId: '1:679344257056:web:66c8c7e25bd359a739a445',
    messagingSenderId: '679344257056',
    projectId: 'todolist-ee306',
    authDomain: 'todolist-ee306.firebaseapp.com',
    storageBucket: 'todolist-ee306.firebasestorage.app',
    measurementId: 'G-D5TBH1NZ2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf08Os5AzQlXHeVGrMT5HU04Vpbcv9keM',
    appId: '1:679344257056:android:23e0f92b27d8996139a445',
    messagingSenderId: '679344257056',
    projectId: 'todolist-ee306',
    storageBucket: 'todolist-ee306.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwnv-Y5aKztV_YrKWxnNxaj6vkmJXqQAg',
    appId: '1:679344257056:ios:3f2fdb69740ac12839a445',
    messagingSenderId: '679344257056',
    projectId: 'todolist-ee306',
    storageBucket: 'todolist-ee306.firebasestorage.app',
    iosBundleId: 'com.example.toDoListMvvm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwnv-Y5aKztV_YrKWxnNxaj6vkmJXqQAg',
    appId: '1:679344257056:ios:3f2fdb69740ac12839a445',
    messagingSenderId: '679344257056',
    projectId: 'todolist-ee306',
    storageBucket: 'todolist-ee306.firebasestorage.app',
    iosBundleId: 'com.example.toDoListMvvm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvFARR9V-OkyVjIlk7Dr1SeXEbBW6lWk4',
    appId: '1:679344257056:web:dffc7d12ed62899739a445',
    messagingSenderId: '679344257056',
    projectId: 'todolist-ee306',
    authDomain: 'todolist-ee306.firebaseapp.com',
    storageBucket: 'todolist-ee306.firebasestorage.app',
    measurementId: 'G-BXT9ZVHHQ2',
  );

}